/* **********************************************************
	DML de peuplement des tables de bases: AEROPORT, VOL, SEGMENT, PILOTE, AVION, ENVOLEE 
	Fichier MRD        : "NordAir"
	Auteur			   : Sylvie Monjal	
***********************************************************/
	  
USE NORDAIR
GO

/* **********************************************************
	ÉNONCÉS INSERT
***********************************************************/

BEGIN TRANSACTION

SAVE TRANSACTION AEROPORT
/* **********************************************************
	Table "AÉROPORT"
***********************************************************/

INSERT INTO AEROPORT
	VALUES('QSI','SEPT-ILES')

INSERT INTO AEROPORT
	VALUES('QGA','GASPE')

INSERT INTO AEROPORT
	VALUES('QRY','RIMOUSKI')

INSERT INTO AEROPORT
	VALUES('QBC','BAIE-COMEAU')

INSERT INTO AEROPORT
	VALUES('QMJ','MONT-JOLI')

INSERT INTO AEROPORT
	VALUES('QHP','HAVRE SAINT-PIERRE')

SAVE TRANSACTION VOL
/* **********************************************************
	Table "VOL"
***********************************************************/

INSERT INTO VOL
	VALUES(1822,NULL)

INSERT INTO VOL
	VALUES(1823,NULL)

INSERT INTO VOL
	VALUES(1922,NULL)

INSERT INTO VOL
	VALUES(1923,NULL)

SAVE TRANSACTION SEGMENT
/* **********************************************************
	Table "SEGMENT"
***********************************************************/
-- VOL 1822
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('A',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1822),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QMJ'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		 '06:00',
		 50)

/*
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	SELECT
		'A',
		VOL.ID_VOL,
		AER_DEP.ID_AEROPORT,
		AER_DEST.ID_AEROPORT,
		 TO_DATE('06:00','HH24:MI'),
		 50
	FROM
		VOL
			CROSS JOIN AEROPORT AER_DEP
			CROSS JOIN AEROPORT AER_DEST
	WHERE
		VOL.NO_VOL = 1822 AND
		AER_DEP.ACR_AEROPORT = 'QMJ' AND
		AER_DEST.ACR_AEROPORT = 'QBC'
*/
		
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('B',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1822),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		 '07:00',
		 60);
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('C',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1822),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		 '08:00',
		 30)
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('D',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1822),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QHP'),
		 '09:00',
		 40)
-- VOL 1823
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('A',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1823),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QHP'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		 '17:00',
		 40)
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('B',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1823),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		 '18:00',
		 35)
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
	 	('C',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1823),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		 '19:00',
		 55)
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('D',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1823),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QMJ'),
		 '20:00',
		 45)
-- VOL 1922	 
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('A',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1922),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QMJ'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		 '17:30',
		 50)
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('B',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1922),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		 '18:30',
		 60)
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('C',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1922),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		 '19:30',
		 30)
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('D',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1922),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QHP'),
		 '20:30',
		 40)
-- VOL 1923
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('A',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1923),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QHP'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		 '05:30',
		 40)
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('B',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1923),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		 '06:30',
		 35)
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('C',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1923),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		 '07:30',
		 55)
INSERT INTO
	SEGMENT
		(ORDRE_SEGMENT,
		 ID_VOL,
		 AEROPORT_DEPART,
		 AEROPORT_DESTINATION,
		 HEURE_DEPART,
		 DUREE_VOL)
	VALUES
		('D',
		 (SELECT ID_VOL FROM VOL WHERE NO_VOL = 1923),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		 (SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QMJ'),
		 '08:30',
		 45)

SAVE TRANSACTION PILOTE
/* **********************************************************
	Table "PILOTE"
***********************************************************/
INSERT INTO
	PILOTE
		(NO_PILOTE,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(22,
		 'LAVIGNE',
		 'ROGER',
		 '44 DUROCHER', 
		 '(418)666-3333')
INSERT INTO
	PILOTE
		(NO_PILOTE,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(34,
		 'LATRIMOUILLE',
		 'ANDRE',
		 '5353 MONFORT',
		 '(540)555-3344')
INSERT INTO
	PILOTE
		(NO_PILOTE,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(55,
		 'LAVERTU',
		 'MARIE',
		 '5353 MONFORT',
		 '(540)555-3344')
INSERT INTO
	PILOTE
		(NO_PILOTE,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(61,
		 'GENEST',
		 'CLAUDINE',
		 '1722 CRESCENT, APP 3',
		 '(514)555-1234')
--ROLLBACK TRANSACTION PILOTE

SAVE TRANSACTION AVION
/* **********************************************************
	Table "AVION"
***********************************************************/
INSERT INTO AVION
	VALUES('CADM',32)

INSERT INTO AVION
	VALUES('COPA',48)


SAVE TRANSACTION ENVOLEE
/* **********************************************************
	Table "ENVOLÉE"
***********************************************************/
/* **********************************************************
	PEUPLEMENT DE ENVOLEE EN 8 INSTRUCTIONS
************************************************************/
INSERT INTO
	ENVOLEE 
		(DATE_ENVOLEE,
		 ID_SEGMENT,
		 ID_AVION,
		 ID_PILOTE)
	SELECT
		'2022-05-13',
		SEGMENT.ID_SEGMENT,
		AVION.ID_AVION,
		PILOTE.ID_PILOTE
	FROM
		SEGMENT
			INNER JOIN VOL
				ON SEGMENT.ID_VOL = VOL.ID_VOL
			CROSS JOIN AVION
			CROSS JOIN PILOTE
	WHERE
		(AVION.APPEL_AVION = 'CADM'
		 AND
		 PILOTE.NO_PILOTE = 22
		 AND
		 ( VOL.NO_VOL = 1922 OR VOL.NO_VOL = 1923 )
		)
		OR
		(AVION.APPEL_AVION = 'COPA'
		 AND
		 PILOTE.NO_PILOTE = 55
		 AND
		 ( VOL.NO_VOL = 1822 OR VOL.NO_VOL = 1823 )
		)

INSERT INTO
	ENVOLEE 
		(DATE_ENVOLEE,
		 ID_SEGMENT,
		 ID_AVION,
		 ID_PILOTE)
	SELECT
		'2022-05-14',
		SEGMENT.ID_SEGMENT,
		AVION.ID_AVION,
		PILOTE.ID_PILOTE
	FROM
		SEGMENT
			INNER JOIN VOL
				ON SEGMENT.ID_VOL = VOL.ID_VOL
			CROSS JOIN AVION
			CROSS JOIN PILOTE
WHERE
		(AVION.APPEL_AVION = 'CADM'
		 AND
		 PILOTE.NO_PILOTE = 22
		 AND
		 ( VOL.NO_VOL = 1922 OR VOL.NO_VOL = 1923 )
		)
		OR
		(AVION.APPEL_AVION = 'COPA'
		 AND
		 PILOTE.NO_PILOTE = 55
		 AND
		 ( VOL.NO_VOL = 1822 OR VOL.NO_VOL = 1823 )
		)

INSERT INTO
	ENVOLEE 
		(DATE_ENVOLEE,
		 ID_SEGMENT,
		 ID_AVION,
		 ID_PILOTE)
	SELECT
		'2022-05-15',
		SEGMENT.ID_SEGMENT,
		AVION.ID_AVION,
		PILOTE.ID_PILOTE
	FROM
		SEGMENT
			INNER JOIN VOL
				ON SEGMENT.ID_VOL = VOL.ID_VOL
			CROSS JOIN AVION
			CROSS JOIN PILOTE
	WHERE
		(AVION.APPEL_AVION = 'CADM'
		 AND
		 PILOTE.NO_PILOTE = 22
		 AND
		 ( VOL.NO_VOL = 1922 OR VOL.NO_VOL = 1923 )
		)
		OR
		(AVION.APPEL_AVION = 'COPA'
		 AND
		 PILOTE.NO_PILOTE = 55
		 AND
		 ( VOL.NO_VOL = 1822 OR VOL.NO_VOL = 1823 )
		)

INSERT INTO
	ENVOLEE 
		(DATE_ENVOLEE,
		 ID_SEGMENT,
		 ID_AVION,
		 ID_PILOTE)
	SELECT
		'2022-05-16',
		SEGMENT.ID_SEGMENT,
		AVION.ID_AVION,
		PILOTE.ID_PILOTE
	FROM
		SEGMENT
			INNER JOIN VOL
				ON SEGMENT.ID_VOL = VOL.ID_VOL
			CROSS JOIN AVION
			CROSS JOIN PILOTE
	WHERE
		(AVION.APPEL_AVION = 'CADM'
		 AND
		 PILOTE.NO_PILOTE = 22
		 AND
		 ( VOL.NO_VOL = 1922 OR VOL.NO_VOL = 1923 )
		)
		OR
		(AVION.APPEL_AVION = 'COPA'
		 AND
		 PILOTE.NO_PILOTE = 55
		 AND
		 ( VOL.NO_VOL = 1822 OR VOL.NO_VOL = 1823 )
		)

INSERT INTO
	ENVOLEE 
		(DATE_ENVOLEE,
		 ID_SEGMENT,
		 ID_AVION,
		 ID_PILOTE)
	SELECT
		'2022-05-17',
		SEGMENT.ID_SEGMENT,
		AVION.ID_AVION,
		PILOTE.ID_PILOTE
	FROM
		SEGMENT
			INNER JOIN VOL
				ON SEGMENT.ID_VOL = VOL.ID_VOL
			CROSS JOIN AVION
			CROSS JOIN PILOTE
	WHERE
		(AVION.APPEL_AVION = 'CADM'
		 AND
		 PILOTE.NO_PILOTE = 34
		 AND ( VOL.NO_VOL = 1822 OR VOL.NO_VOL = 1923 )
		)
		OR
		(AVION.APPEL_AVION = 'COPA'
		 AND
		 PILOTE.NO_PILOTE = 61
		 AND ( VOL.NO_VOL = 1823 OR VOL.NO_VOL = 1922 )
		)

INSERT INTO
	ENVOLEE 
		(DATE_ENVOLEE,
		 ID_SEGMENT,
		 ID_AVION,
		 ID_PILOTE)
	SELECT
		'2022-05-18',
		SEGMENT.ID_SEGMENT,
		AVION.ID_AVION,
		PILOTE.ID_PILOTE
	FROM
		SEGMENT
			INNER JOIN VOL
				ON SEGMENT.ID_VOL = VOL.ID_VOL
			CROSS JOIN AVION
			CROSS JOIN PILOTE
	WHERE
		(AVION.APPEL_AVION = 'CADM'
		 AND
		 PILOTE.NO_PILOTE = 34
		 AND ( VOL.NO_VOL = 1822 OR VOL.NO_VOL = 1923 )
		)
		OR
		(AVION.APPEL_AVION = 'COPA'
		 AND
		 PILOTE.NO_PILOTE = 61
		 AND ( VOL.NO_VOL = 1823 OR VOL.NO_VOL = 1922 )
		)

INSERT INTO
	ENVOLEE 
		(DATE_ENVOLEE,
		 ID_SEGMENT,
		 ID_AVION,
		 ID_PILOTE)
	SELECT
		'2022-05-19',
		SEGMENT.ID_SEGMENT,
		AVION.ID_AVION,
		PILOTE.ID_PILOTE
	FROM
		SEGMENT
			INNER JOIN VOL
				ON SEGMENT.ID_VOL = VOL.ID_VOL
			CROSS JOIN AVION
			CROSS JOIN PILOTE
	WHERE
		(AVION.APPEL_AVION = 'CADM'
		 AND
		 PILOTE.NO_PILOTE = 34
		 AND ( VOL.NO_VOL = 1822 OR VOL.NO_VOL = 1923 )
		)
		OR
		(AVION.APPEL_AVION = 'COPA'
		 AND
		 PILOTE.NO_PILOTE = 61
		 AND ( VOL.NO_VOL = 1823 OR VOL.NO_VOL = 1922 )
		)

INSERT INTO
	ENVOLEE 
		(DATE_ENVOLEE,
		 ID_SEGMENT,
		 ID_AVION,
		 ID_PILOTE)
	SELECT
		'2022-05-20',
		SEGMENT.ID_SEGMENT,
		AVION.ID_AVION,
		PILOTE.ID_PILOTE
	FROM
		SEGMENT
			INNER JOIN VOL
				ON SEGMENT.ID_VOL = VOL.ID_VOL
			CROSS JOIN AVION
			CROSS JOIN PILOTE
	WHERE
		(AVION.APPEL_AVION = 'CADM'
		 AND
		 PILOTE.NO_PILOTE = 34
		 AND ( VOL.NO_VOL = 1822 OR VOL.NO_VOL = 1923 )
		)
		OR
		(AVION.APPEL_AVION = 'COPA'
		 AND
		 PILOTE.NO_PILOTE = 61
		 AND ( VOL.NO_VOL = 1823 OR VOL.NO_VOL = 1922 )
		)


-- ROLLBACK TRANSACTION ENVOLEE
COMMIT