/* **********************************************************
	Script DML  : peuplement des tables PASSAGER, RESERVATION et RESERVATION_ENVOLEE
				  PARTIE 2
	Fichier MRD : "NordAir"
	Auteur	    : Sylvie Monjal 
********************************************************** */

/* AVANT L'EXÉCUTION DE CE SCRIPT No 2:
	- EXÉCUTEZ LE SCRIPT No 1 "Vacances-NordAirDMLInsertTReservation1.sql" */

USE NORDAIR
GO	

BEGIN TRANSACTION

SAVE TRANSACTION RESERVATION2
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Duval',
		 'Philippe', 
		 '4547 St-Jules',
		 '(418)555-3234' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-04-13',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '02A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Lapierre',
		 'Guillaume', 
		 '1110 Rene',
		 '(418)555-3232' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-04-18',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '02B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '03C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1823
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Poussier',
		 'Genevieve', 
		 '12345 Germain',
		 '(418)555-3245' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-04-22',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '03C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		(SEGMENT.ORDRE_SEGMENT = 'C')
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '04D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Mallet',
		 'Sylvain', 
		 '31 Royale',
		 '(418)555-5532' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-04-11',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '05A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822 
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '06B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-17'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1923
---       
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Saucier',
		 'Jean-Francois', 
		 '10235 St-Laurent',
		 '(418)555-4643' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-04-20',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '07A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '07A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '07A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '07A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '04C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-19'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '04C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-19'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '04C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-19'
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '04D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-20'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1923
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Lagace',
		 'Mathieu', 
		 '2022 Levesque',
		 '(418)555-5778' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-04-20',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '02A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-18'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1822
---     
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Blanchette',
		 'Marc', 
		 '4340 Elzear',
		 '(418)555-3667' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-01',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '08A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-19'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '03A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-19'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1822
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Aspiros',
		 'Charles', 
		 '12B duFort',
		 '(418)555-3265' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-01',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '03A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-17'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1822
---    
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Picard',
		 'Maxime', 
		 '1229 Jeanne d''Arc',
		 '(418)555-4573' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-02',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-18'
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1922
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '08A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-18'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1922
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '06A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-19'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1923
---   
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Richard',
		 'Jean-Francois', 
		 '4451 St-Cyrille',
		 '(418)555-3746' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-03',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '02A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-19'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1823
---      
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Dube',
		 'Jason', 
		 '1044 Principale',
		 '(418)555-9878' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-04',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-19'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '09D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-20'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1822
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Lapointe-Girard',
		 'etienne', 
		 '4440 Beausejour',
		 '(418)555-4987' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-05',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '07C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT IN ('A','B','C')
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '02A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-18'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Mercier',
		 'Nicolas', 
		 '222 Dupont',
		 '(418)555-1232' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-06',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-19'
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1823
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Aubert',
		 'Vincent', 
		 '1233 Albert',
		 '(418)555-3765' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-05',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1922
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Ouellet',
		 'Remi', 
		 '9857 St-Louis',
		 '(418)555-6335' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-04',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '05D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		(SEGMENT.ORDRE_SEGMENT = 'A' OR SEGMENT.ORDRE_SEGMENT = 'B')
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-17'
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1923
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Ouellette',
		 'Pierre', 
		 '4851 duRoy',
		 '(418)555-8730' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-03',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '08D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT IN ('A','B','C')
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '03A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-18'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-20'
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1923
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Pelletier',
		 'Nathalie', 
		 '3654C duCarre',
		 '(418)555-3277' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-02',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-18'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1922
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '06C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-20'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1922
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Tremblay',
		 'Sebastien', 
		 '3656D duCarre',
		 '(418)555-3367' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-02',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '10C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT IN ('A','B','C','D')
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-18'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '06D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-20'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Talbot',
		 'Remi', 
		 '4654D duRectangle',
		 '(418)555-3867' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-02',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '10D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT IN ('A','B','C','D')
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '02A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-18'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '07B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-20'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Rouillard',
		 'Guy', 
		 '75B, de LaLiberte',
		 '(418)555-3067' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-02',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '03A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-18'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '08B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-20'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822
---
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-02',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '03A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-15'
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '08B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1823

--ROLLBACK TRANSACTION RESERVATION2
COMMIT
