/* **********************************************************
	Script DML  : peuplement des tables PASSAGER, RESERVATION et RESERVATION_ENVOLEE
				  PARTIE 1
	Fichier MRD : "NordAir"
	Auteur	    : Sylvie Monjal 
********************************************************** */

/* AVANT L'EXÉCUTION DE CE SCRIPT No 1:
    - EXÉCUTEZ LE SCRIPT No 1 "NordAirDMLInsertTablesBases.sql"
	  pour peupler les tables: AEROPORT, VOL, SEGMENT, PILOTE, AVION, ENVOLEE */

/* APRÈS L'EXÉCUTION DE CE SCRIPT No 1:
	- EXÉCUTEZ LE SCRIPT "NordAirDMLInsertTReservation2.sql" */

USE NORDAIR
GO	

BEGIN TRANSACTION	

SAVE TRANSACTION RESERVATION1
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Barbeau',
		 'Isabelle', 
		 '4545 St-Jules',
		 '(418)555-3233' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-04-13',
		 IDENT_CURRENT('PASSAGER'))

INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822
-- 
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Berthiaume',
		 'Jonny', 
		 '1100 Rene',
		 '(418)555-3222' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-04-18',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '02B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '03C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1823
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Bolduc',
		 'Sebastien', 
		 '1234 Germain',
		 '(418)555-3244' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-04-22',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '04D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('BrindAmour',
		 'Jean-Francois', 
		 '33 Royale',
		 '(418)555-5533' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-04-11',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '05A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '06B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-14'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1923
---          
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Desjardins',
		 'Francois', 
		 '10225 St-Laurent',
		 '(418)555-4633' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-04-20',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '07A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '07A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '07A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '07A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '04C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '04C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '04C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '04D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-17'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1923
--
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Cote',
		 'Mathieu', 
		 '2021 Levesque',
		 '(418)555-5678' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-01',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '02A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-15'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1922
---     
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Fortin',
		 'Jean-Philippe', 
		 '4440 Elzear',
		 '(418)555-3567' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-01',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '08A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '03A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1822
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Harnois',
		 'Stephane J.', 
		 '12a duFort',
		 '(418)555-3255' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-01',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-14'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1822
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Fortin',
		 'Mathieu', 
		 '1223 Jeanne d''Arc',
		 '(418)555-4563' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-02',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '03C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		(SEGMENT.ORDRE_SEGMENT = 'A' OR SEGMENT.ORDRE_SEGMENT = 'B')
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-15'
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1922
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '08A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-15'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1922
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '06B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1923
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Jobin',
		 'Samuel', 
		 '445 St-Cyrille',
		 '(418)555-3786' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-03',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-16'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1823
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Ratte',
		 'Francois', 
		 '1024 Principale',
		 '(418)555-9876' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-04',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-17'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '09D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-18'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1822
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Gregoire',
		 'Pierre-Luc', 
		 '4040 Beausejour',
		 '(418)555-0987' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-05',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '07D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT IN ('A','B','C')
		AND
		VOL.NO_VOL = 1923
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-18'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822
---     
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Dostie-Proulx',
		 'Pierre-Luc', 
		 '22 Dupont',
		 '(418)555-1231' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-06',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-18'
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1823
---
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Nadeau',
		 'Michel', 
		 '123 Albert',
		 '(418)555-8765' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-05',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1922
--- 
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Tremblay',
		 'Vincent', 
		 '9856 St-Louis',
		 '(418)555-6935' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-04',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1923
---  
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Mercier',
		 'David', 
		 '4850 duRoy',
		 '(418)555-8700' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-03',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-13'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-20'
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1923
---    
INSERT INTO
	PASSAGER
		(NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		('Dionne',
		 'Marjorie', 
		 '3654D duCarre',
		 '(418)555-3267' )      
INSERT INTO
	RESERVATION
		(DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		('2022-05-02',
		 IDENT_CURRENT('PASSAGER'))
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-18'
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1922
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 IDENT_CURRENT('RESERVATION'),
		 ENVOLEE.ID_ENVOLEE,
		 '06B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = '2022-05-20'
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1922

--ROLLBACK TRANSACTION RESERVATION1
COMMIT