/* **********************************************************
	DML Insert - SCRIPT No 1
	Schéma MRD:	"Cas Village Vacances"
	Auteur:		Sylvie Monjal - Mathieu Simard  	
***********************************************************/
USE VILLAGE_VACANCES
GO
/*===============================================================================
     Table CATÉGORIE_VILLAGE: 3 catégories de village
===============================================================================*/	
INSERT INTO
	CATEGORIE_VILLAGE
		(
         NO_CATEGORIE,
		 DESCRIPTION)
	VALUES
		(
         1,
		 'tennis, piscine, mini-golf, golf, sauna, garderie');
INSERT INTO
	CATEGORIE_VILLAGE
		(
         NO_CATEGORIE,
		 DESCRIPTION)
	VALUES
		(
         2,
		 'tennis, piscine, golf, sauna');
INSERT INTO
	CATEGORIE_VILLAGE
		(
         NO_CATEGORIE,
		 DESCRIPTION)
	VALUES
		(
         3,
		 'tennis, piscine, garderie');

/*===============================================================================
     Table TYPE_LOGEMENT: 11 types de logement
===============================================================================*/	

INSERT INTO
	TYPE_LOGEMENT
		(
         CODE_TYPE_LOGEMENT,
		 DESCRIPTION,
		 NB_MAX_PERSONNES)
	VALUES
		(
         'A1',
		 'Chambre 4 personnes avec douche',
		 4);
INSERT INTO
	TYPE_LOGEMENT
		(
         CODE_TYPE_LOGEMENT,
		 DESCRIPTION,
		 NB_MAX_PERSONNES)
	VALUES
		(
         'A2',
		 'Chambre 4 personnes avec bain',
		 4);
INSERT INTO
	TYPE_LOGEMENT
		(
         CODE_TYPE_LOGEMENT,
		 DESCRIPTION,
		 NB_MAX_PERSONNES)
	VALUES
		(
         'A3',
		 'Chambre 2 personnes avec bain',
		 2);
INSERT INTO
	TYPE_LOGEMENT
		(
         CODE_TYPE_LOGEMENT,
		 DESCRIPTION,
		 NB_MAX_PERSONNES)
	VALUES
		(
         'A4',
		 'Chambre 1 personne avec bain',
		 1);
INSERT INTO
	TYPE_LOGEMENT
		(
         CODE_TYPE_LOGEMENT,
		 DESCRIPTION,
		 NB_MAX_PERSONNES)
	VALUES
		(
         'B1',
		 'Suite 1 personne',
		 1);
INSERT INTO
	TYPE_LOGEMENT
		(
         CODE_TYPE_LOGEMENT,
		 DESCRIPTION,
		 NB_MAX_PERSONNES)
	VALUES
		(
         'B2',
		 'Suite 2 personnes',
		 2);
INSERT INTO
	TYPE_LOGEMENT
		(
         CODE_TYPE_LOGEMENT,
		 DESCRIPTION,
		 NB_MAX_PERSONNES)
	VALUES
		(
         'C1',
		 'Bungalow 4 personnes',
		 4);
INSERT INTO
	TYPE_LOGEMENT
		(
         CODE_TYPE_LOGEMENT,
		 DESCRIPTION,
		 NB_MAX_PERSONNES)
	VALUES
		(
         'C2',
		 'Bungalow 2 personnes',
		 2);
INSERT INTO
	TYPE_LOGEMENT
		(
         CODE_TYPE_LOGEMENT,
		 DESCRIPTION,
		 NB_MAX_PERSONNES)
	VALUES
		(
         'D1',
		 'Chalet 6 personnes',
		 6);
INSERT INTO
	TYPE_LOGEMENT
		(
         CODE_TYPE_LOGEMENT,
		 DESCRIPTION,
		 NB_MAX_PERSONNES)
	VALUES
		(
         'D2',
		 'Chalet 4 personnes',
		 4);
INSERT INTO
	TYPE_LOGEMENT
		(
         CODE_TYPE_LOGEMENT,
		 DESCRIPTION,
		 NB_MAX_PERSONNES)
	VALUES
		(
         'D3',
		 'Chalet 2 personnes',
		 2);

/*===============================================================================
     Table TARIF_NUITEE:
===============================================================================*/	

-- Catégorie 1
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 1),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A1'),
		 45);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 1),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A2'),
		 50);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 1),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A3'),
		 60);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 1),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A4'),
		 70);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 1),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B1'),
		 75);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 1),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B2'),
		 85);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 1),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C1'),
		 40);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 1),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 35);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 1),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D1'),
		 40);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 1),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D2'),
		 50);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 1),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D3'),
		 80);
-- Catégorie 2
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 2),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A1'),
		 40);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 2),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A2'),
		 45);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 2),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A3'),
		 50);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 2),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A4'),
		 60);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 2),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B1'),
		 65);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 2),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B2'),
		 75);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 2),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C1'),
		 30);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 2),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 40);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 2),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D1'),
		 30);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 2),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D2'),
		 40);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 2),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D3'),
		 60);
-- Catégorie 3
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 3),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A1'),
		 35);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 3),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A2'),
		 40);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 3),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A3'),
		 45);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 3),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A4'),
		 55);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 3),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B1'),
		 60);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 3),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B2'),
		 70);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 3),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C1'),
		 25);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 3),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 35);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 3),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D1'),
		 25);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 3),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D2'),
		 35);
INSERT INTO
	TARIF_NUITEE
		(ID_CATEGORIE_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 TARIF_UNITAIRE)
	VALUES
		((SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 3),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D3'),
		 55);
		 
/*===============================================================================
     Table VILLAGE: 4 villages
===============================================================================*/	

INSERT INTO
	VILLAGE
		(
         NOM_VILLAGE,
		 VILLE,
		 PAYS,
		 ID_CATEGORIE_VILLAGE,
		 PRIX_TRANSPORT)
	VALUES
		(
         'Casa-Dali',
		 'Figueiras',
		 'Espagne',
		 (SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 3),
		 1059);
INSERT INTO
	VILLAGE
		(
         NOM_VILLAGE,
		 VILLE,
		 PAYS,
		 ID_CATEGORIE_VILLAGE,
		 PRIX_TRANSPORT)
	VALUES
		(
         'Porto-Nuevo',
		 'Valencia',
		 'Espagne',
		 (SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 2),
		 949);
INSERT INTO
	VILLAGE
		(
         NOM_VILLAGE,
		 VILLE,
		 PAYS,
		 ID_CATEGORIE_VILLAGE,
		 PRIX_TRANSPORT)
	VALUES
		(
         'Cuidad Blanca',
		 'Barcelona',
		 'Espagne',
		 (SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 3),
		 800);
INSERT INTO
	VILLAGE
		(
         NOM_VILLAGE,
		 VILLE,
		 PAYS,
		 ID_CATEGORIE_VILLAGE,
		 PRIX_TRANSPORT)
	VALUES
		(
         'Kouros',
		 'Corfou',
		 'Grèce',
		 (SELECT ID_CATEGORIE_VILLAGE FROM CATEGORIE_VILLAGE WHERE NO_CATEGORIE = 3),
		 1239);

/*===============================================================================
     Table LOGEMENT
===============================================================================*/	

/* logements Village Casa-Dali */
-- logements Casa-Dali - type B2
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         8,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         9,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         11,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         18,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         19,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B2'),
		 NULL);
-- logements Casa-Dali - type C2
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         100,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         101,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         102,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 NULL);
-- logements Casa-Dali - type D1
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         103,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         104,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D1'),
		 NULL);
-- logements Casa-Dali - type D2
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         105,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         106,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         107,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         108,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         109,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Casa-Dali'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D2'),
		 NULL);
/* logements Village Porto-Nuevo */
-- logements Porto-Nuevo - type C2
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         1,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Porto-Nuevo'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         2,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Porto-Nuevo'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         3,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Porto-Nuevo'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         108,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Porto-Nuevo'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 NULL);
/* logements Village Cuidad Blanca */
-- logements Cuidad Blanca - type A1
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         1,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Cuidad Blanca'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         2,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Cuidad Blanca'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A1'),
		 NULL);
-- logements Ciudad Blanca - type A2
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         3,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Cuidad Blanca'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A2'),
		 NULL);
-- logements Ciudad Blanca - type A3
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         10,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Cuidad Blanca'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A3'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         20,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Cuidad Blanca'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A3'),
		 NULL);

/* logements Village Kouros */
-- logements Kouros - type A1
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         4,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         5,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         6,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         7,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A1'),
		 NULL);
-- logements Kouros - type A3
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         10,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A3'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         11,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A3'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         13,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A3'),
		 NULL);
-- logements Kouros - type A4
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         1,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A4'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         2,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A4'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         3,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A4'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         16,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A4'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         17,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'A4'),
		 NULL);
-- logements Kouros - type B2
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         8,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         9,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         18,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         19,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'B2'),
		 NULL);
-- logements Kouros - type C1
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         106,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         107,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         108,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         109,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         110,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         111,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         112,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C1'),
		 NULL);
-- logements Kouros - type C2
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         100,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         101,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         102,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         103,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         104,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         105,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'C2'),
		 NULL);
-- logements Kouros - type D1
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         113,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         114,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         115,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         116,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         117,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D1'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         118,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D1'),
		 NULL);
-- logements Kouros - type D2
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         119,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         120,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         121,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         122,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D2'),
		 NULL);
INSERT INTO
	LOGEMENT
		(
         NO_LOGEMENT,
		 ID_VILLAGE,
		 ID_TYPE_LOGEMENT,
		 COMMENTAIRE)
	VALUES
		(
         123,
		 (SELECT ID_VILLAGE FROM VILLAGE WHERE NOM_VILLAGE = 'Kouros'),
		 (SELECT ID_TYPE_LOGEMENT FROM TYPE_LOGEMENT WHERE CODE_TYPE_LOGEMENT = 'D2'),
		 NULL);

