/* **********************************************************
	DDL de création des objets de la base de données
	Schéma MRD         : "Villages Vacances" - Script no 1
	Par                : Sylvie Monjal - Mathieu Simard
********************************************************** */
CREATE DATABASE VILLAGE_VACANCES
GO

USE VILLAGE_VACANCES
GO

/* **********************************************************
	Table "CATEGORIE_VILLAGE"
********************************************************** */
CREATE TABLE CATEGORIE_VILLAGE (
	ID_CATEGORIE_VILLAGE    DECIMAL(1,0)    IDENTITY(1,1) NOT NULL, 
	NO_CATEGORIE	        SMALLINT		NOT NULL,
	DESCRIPTION		        VARCHAR(50)		NOT NULL,
	CONSTRAINT PK_CATEGORIE_VILLAGE
		PRIMARY KEY (ID_CATEGORIE_VILLAGE),
	CONSTRAINT U1_CATEGORIE_VILLAGE
		UNIQUE (NO_CATEGORIE)
)

/* **********************************************************
	Table "TYPE_LOGEMENT"
********************************************************** */
CREATE TABLE TYPE_LOGEMENT(
	ID_TYPE_LOGEMENT        DECIMAL(2,0)	IDENTITY(1,1) NOT NULL,
	CODE_TYPE_LOGEMENT	    VARCHAR(2)		NOT NULL,
	DESCRIPTION			    VARCHAR(35)		NOT NULL,
	NB_MAX_PERSONNES	    SMALLINT		NOT NULL,
	CONSTRAINT PK_TYPE_LOGEMENT
		PRIMARY KEY (ID_TYPE_LOGEMENT),
	CONSTRAINT U1_TYPE_LOGEMENT
		UNIQUE (CODE_TYPE_LOGEMENT)
)


/* **********************************************************
	Table "VILLAGE"
********************************************************** */
CREATE TABLE VILLAGE (
	ID_VILLAGE		        DECIMAL(2,0)	IDENTITY(1,1) NOT NULL,
	NOM_VILLAGE		        VARCHAR(15)		NOT NULL,
	VILLE			        VARCHAR(10)		NOT NULL,
	PAYS			        VARCHAR(10)		NOT NULL,
	PRIX_TRANSPORT	        DECIMAL(6,2)	NOT NULL,
	ID_CATEGORIE_VILLAGE	DECIMAL(1,0)	NOT NULL,
	CONSTRAINT PK_VILLAGE
		PRIMARY KEY (ID_VILLAGE),
	CONSTRAINT U1_VILLAGE
		UNIQUE (NOM_VILLAGE),
    CONSTRAINT FK_VILL_CATEGORIE_VILL
		FOREIGN KEY (ID_CATEGORIE_VILLAGE)
		REFERENCES CATEGORIE_VILLAGE(ID_CATEGORIE_VILLAGE)
)

/* **********************************************************
	Table "LOGEMENT"
********************************************************** */
CREATE TABLE LOGEMENT(
	ID_LOGEMENT             DECIMAL(4,0)	IDENTITY(1,1) NOT NULL,  
	NO_LOGEMENT			    SMALLINT		NOT NULL,
	ID_VILLAGE			    DECIMAL(2,0)	NOT NULL,
	ID_TYPE_LOGEMENT        DECIMAL(2,0)		NOT NULL,
	COMMENTAIRE			    VARCHAR(125)	NULL,
	CONSTRAINT PK_LOGEMENT
		PRIMARY KEY (ID_LOGEMENT),
    CONSTRAINT U1_LOGEMENT
		UNIQUE (NO_LOGEMENT, ID_VILLAGE),
	CONSTRAINT FK_LOG_TYPE_LOGEMENT
		FOREIGN KEY (ID_TYPE_LOGEMENT)
		REFERENCES TYPE_LOGEMENT (ID_TYPE_LOGEMENT),
	CONSTRAINT FK_LOG_VILLAGE
		FOREIGN KEY (ID_VILLAGE)
		REFERENCES VILLAGE (ID_VILLAGE)
)

/* **********************************************************
	Table "CLIENT"
********************************************************** */
CREATE TABLE CLIENT(
	ID_CLIENT			DECIMAL(6,0)	IDENTITY(1,1) NOT NULL,	
	NOM					VARCHAR(25)		NOT NULL,
	PRENOM				VARCHAR(25)		NOT NULL,
	SEXE				CHAR(1)			NOT NULL,
	ADRESSE				VARCHAR(50)		NULL,
	TEL_DOMICILE		DECIMAL(10,0)	NOT NULL
	CONSTRAINT PK_CLIENT
		PRIMARY KEY (ID_CLIENT)
)

/* **********************************************************
	Table "RESERVATION"
********************************************************** */
CREATE TABLE RESERVATION(
	ID_RESERVATION		DECIMAL(7,0) IDENTITY(1000,1) NOT NULL,
	DATE_RESERVATION	DATETIME DEFAULT GETDATE()	NOT NULL,
	ID_CLIENT			DECIMAL(6,0)				NOT NULL,
	ID_VILLAGE			DECIMAL(2,0)				NOT NULL,
	CONSTRAINT PK_RESERVATION
		PRIMARY KEY (ID_RESERVATION),
	CONSTRAINT FK_RES_CLIENT
		FOREIGN KEY (ID_CLIENT)
		REFERENCES CLIENT (ID_CLIENT),
	CONSTRAINT FK_RES_VILLAGE
		FOREIGN KEY (ID_VILLAGE)
		REFERENCES VILLAGE (ID_VILLAGE)
)


/* **********************************************************
	Table "SEJOUR"
********************************************************** */
CREATE TABLE SEJOUR(
	ID_SEJOUR   		DECIMAL(10,0)	IDENTITY(1,1) NOT NULL,		
	DATE_SEJOUR			DATETIME		NOT NULL,
	ID_LOGEMENT			DECIMAL(4,0)	NOT NULL,
	ID_RESERVATION		DECIMAL(7,0)	NOT NULL,
	NB_PERSONNES		SMALLINT		NOT NULL,
	CONSTRAINT PK_SEJOUR
		PRIMARY KEY (ID_SEJOUR),
	CONSTRAINT U1_SEJOUR
		UNIQUE (DATE_SEJOUR, ID_LOGEMENT),
	CONSTRAINT FK_SEJOUR_LOGEMENT
		FOREIGN KEY (ID_LOGEMENT)
		REFERENCES LOGEMENT (ID_LOGEMENT),
	CONSTRAINT FK_SEJOUR_RESERVATION
		FOREIGN KEY (ID_RESERVATION)
		REFERENCES RESERVATION (ID_RESERVATION)
)

/* **********************************************************
	Table "TARIF_NUITEE"
********************************************************** */
CREATE TABLE TARIF_NUITEE(
	ID_CATEGORIE_VILLAGE    DECIMAL(1,0)    NOT NULL,
	ID_TYPE_LOGEMENT        DECIMAL(2,0)	NOT NULL,
	TARIF_UNITAIRE		    DECIMAL(5,2)	NOT NULL,
	CONSTRAINT PK_TARIF_NUITEE_PRIM
		PRIMARY KEY (ID_CATEGORIE_VILLAGE, ID_TYPE_LOGEMENT),
	CONSTRAINT FK_TARIF_CATEG_VILLAGE
		FOREIGN KEY (ID_CATEGORIE_VILLAGE)
		REFERENCES CATEGORIE_VILLAGE (ID_CATEGORIE_VILLAGE),
	CONSTRAINT FK_TARIF_TYPE_LOG
		FOREIGN KEY (ID_TYPE_LOGEMENT)
		REFERENCES TYPE_LOGEMENT (ID_TYPE_LOGEMENT)
)

/*********************************************************
	Contraintes CHECK
**********************************************************/

ALTER TABLE CATEGORIE_VILLAGE
ADD	CONSTRAINT CHK_CAT_VILL_NO_CATEGORIE
		CHECK(NO_CATEGORIE BETWEEN 1 AND 5)

ALTER TABLE TYPE_LOGEMENT
ADD 	CONSTRAINT CHK_TYPE_LOG_CODE	-- 1er caractère=lettre, 2ième caractère=chiffre
		CHECK (SUBSTRING(UPPER(CODE_TYPE_LOGEMENT), 1, 1) BETWEEN 'A' AND 'Z'   -- REGEXP_LIKE(CODE_TYPE_LOGEMENT, '[A-Z][1-9]')
			  AND
			  SUBSTRING(CODE_TYPE_LOGEMENT, 2, 1) BETWEEN '1' AND '9')

ALTER TABLE TYPE_LOGEMENT
ADD	CONSTRAINT CHK_TYPE_LOG_NB_MAX_PERS
		CHECK (NB_MAX_PERSONNES BETWEEN 1 AND 10)

ALTER TABLE VILLAGE
ADD	CONSTRAINT CHK_VILLAGE_PRIX_TRANSPORT
		CHECK(PRIX_TRANSPORT > 0)

ALTER TABLE CLIENT
ADD	CONSTRAINT CHK_CLIENT_SEXE
		CHECK(SEXE IN ('F','M'))

ALTER TABLE TARIF_NUITEE
ADD	CONSTRAINT CHK_TARIF_UNITAIRE
		CHECK (TARIF_UNITAIRE BETWEEN 20 AND 300)